# Generated by Django 4.1.13 on 2024-02-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('price', models.FloatField()),
                ('salePrice', models.FloatField()),
                ('description', models.TextField()),
                ('isActive', models.BooleanField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('modifyAt', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
